version: "3.3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
     - "${POSTGRES_PORT}:5432"
    volumes:
     - ./data:/data/postgres
    command: [ "postgres", "-c", "wal_level=logical" ]
    env_file:
     - .env
    restart: unless-stopped
