version: "3.3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
     - "${POSTGRES_PORT}:5432"
    volumes:
     - ./data:/data/postgres
    env_file:
     - .env
    restart: unless-stopped
