version: "3.3"
services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    volumes:
      - /rabbitmq/data/:/var/lib/rabbitmq/
      - /rabbitmq/log/:/var/log/rabbitmq 
    env_file:
      - docker.env
    restart: unless-stopped
