version: "3.3"
services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '${RABBITMQ_PORT}:5672'
      # HTTP management UI
      - '15672:15672'
    volumes:
      - ./data/:/var/lib/rabbitmq/
      - ./log/:/var/log/rabbitmq 
    env_file:
      - .env
    restart: unless-stopped
