version: '3.7'

services:
  es01:
    image: elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    environment:
      - cluster.name=cinhtau
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "data01:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    restart: unless-stopped
    networks:
      - esnet
  ki01:
    image: kibana:${KIBANA_VERSION}
    container_name: kibana
    hostname: kibana
    ports: ['5601:5601']
    networks: ['esnet']
    depends_on: ['es01']
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_URL=http://es01:9200

networks:
  esnet:
