version: "3"

services:
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
      container_name: elasticsearch
      restart: unless-stopped
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        discovery.type: single-node
        xpack.security.enabled: false
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      volumes:
      - ./data:/usr/share/elasticsearch/data
      healthcheck:
        test: "curl -f http://localhost:9200 || exit 1"