version: '3.7'

services:
  es01:
    image: elasticsearch:8.3.1
    container_name: elasticsearch
    environment:
      - cluster.name=cinhtau
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "data01:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    restart: unless-stopped
 