version: '3.8'
services:
  db:
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_pas$
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./data:/usr/local/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d$
