version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ~/mysql/database:/var/lib/mysql
      - ~/mysql/database/init.sql:/docker-entrypoint-initdb.d/init.sql