version: '3.8'
services:
  db:
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_pas$
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ~/mysql/database:/usr/local/mysql
      - ~/mysql/database/init.sql:/docker-entrypoint-initdb.d$
