version: "3.3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
     - "5432:5432"
    volumes:
     - /postgres/database:/data/postgres
    env_file:
     - docker.env
    restart: unless-stopped
